import { Country } from "@/app/types/auth";

export const countries: Country[] = [
  { name: 'Nigeria', code: '+234', abbr: 'NG', abbr3: 'NGA' },
  { name: 'Kenya', code: '+254', abbr: 'KE', abbr3: 'KEN' },
  { name: 'Afghanistan', code: '+93', abbr: 'AF', abbr3: 'AFG' },
  { name: 'Aland Islands', code: '+358', abbr: 'AX', abbr3: 'ALA' },
  { name: 'Albania', code: '+355', abbr: 'AL', abbr3: 'ALB' },
  { name: 'Algeria', code: '+213', abbr: 'DZ', abbr3: 'DZA' },
  { name: 'American Samoa', code: '+1684', abbr: 'AS', abbr3: 'ASM' },
  { name: 'Andorra', code: '+376', abbr: 'AD', abbr3: 'AND' },
  { name: 'Angola', code: '+244', abbr: 'AO', abbr3: 'AGO' },
  { name: 'Anguilla', code: '+1264', abbr: 'AI', abbr3: 'AIA' },
  { name: 'Antarctica', code: '+672', abbr: 'AQ', abbr3: 'ATA' },
  { name: 'Antigua and Barbuda', code: '+1268', abbr: 'AG', abbr3: 'ATG' },
  { name: 'Argentina', code: '+54', abbr: 'AR', abbr3: 'ARG' },
  { name: 'Armenia', code: '+374', abbr: 'AM', abbr3: 'ARM' },
  { name: 'Aruba', code: '+297', abbr: 'AW', abbr3: 'ABW' },
  { name: 'Australia', code: '+61', abbr: 'AU', abbr3: 'AUS' },
  { name: 'Austria', code: '+43', abbr: 'AT', abbr3: 'AUT' },
  { name: 'Azerbaijan', code: '+994', abbr: 'AZ', abbr3: 'AZE' },
  { name: 'Bahamas', code: '+1242', abbr: 'BS', abbr3: 'BHS' },
  { name: 'Bahrain', code: '+973', abbr: 'BH', abbr3: 'BHR' },
  { name: 'Bangladesh', code: '+880', abbr: 'BD', abbr3: 'BGD' },
  { name: 'Barbados', code: '+1246', abbr: 'BB', abbr3: 'BRB' },
  { name: 'Belarus', code: '+375', abbr: 'BY', abbr3: 'BLR' },
  { name: 'Belgium', code: '+32', abbr: 'BE', abbr3: 'BEL' },
  { name: 'Belize', code: '+501', abbr: 'BZ', abbr3: 'BLZ' },
  { name: 'Benin', code: '+229', abbr: 'BJ', abbr3: 'BEN' },
  { name: 'Bermuda', code: '+1441', abbr: 'BM', abbr3: 'BMU' },
  { name: 'Bhutan', code: '+975', abbr: 'BT', abbr3: 'BTN' },
  { name: 'Bolivia', code: '+591', abbr: 'BO', abbr3: 'BOL' },
  { name: 'Bonaire, Sint Eustatius and Saba', code: '+599', abbr: 'BQ', abbr3: 'BES' },
  { name: 'Bosnia and Herzegovina', code: '+387', abbr: 'BA', abbr3: 'BIH' },
  { name: 'Botswana', code: '+267', abbr: 'BW', abbr3: 'BWA' },
  { name: 'Brazil', code: '+55', abbr: 'BR', abbr3: 'BRA' },
  { name: 'British Indian Ocean Territory', code: '+246', abbr: 'IO', abbr3: 'IOT' },
  { name: 'Brunei Darussalam', code: '+673', abbr: 'BN', abbr3: 'BRN' },
  { name: 'Bulgaria', code: '+359', abbr: 'BG', abbr3: 'BGR' },
  { name: 'Burkina Faso', code: '+226', abbr: 'BF', abbr3: 'BFA' },
  { name: 'Burundi', code: '+257', abbr: 'BI', abbr3: 'BDI' },
  { name: 'Cambodia', code: '+855', abbr: 'KH', abbr3: 'KHM' },
  { name: 'Cameroon', code: '+237', abbr: 'CM', abbr3: 'CMR' },
  { name: 'Canada', code: '+1', abbr: 'CA', abbr3: 'CAN' },
  { name: 'Cape Verde', code: '+238', abbr: 'CV', abbr3: 'CPV' },
  { name: 'Cayman Islands', code: '+1345', abbr: 'KY', abbr3: 'CYM' },
  { name: 'Central African Republic', code: '+236', abbr: 'CF', abbr3: 'CAF' },
  { name: 'Chad', code: '+235', abbr: 'TD', abbr3: 'TCD' },
  { name: 'Chile', code: '+56', abbr: 'CL', abbr3: 'CHL' },
  { name: 'China', code: '+86', abbr: 'CN', abbr3: 'CHN' },
  { name: 'Christmas Island', code: '+61', abbr: 'CX', abbr3: 'CXR' },
  { name: 'Cocos (Keeling) Islands', code: '+672', abbr: 'CC', abbr3: 'CCK' },
  { name: 'Colombia', code: '+57', abbr: 'CO', abbr3: 'COL' },
  { name: 'Comoros', code: '+269', abbr: 'KM', abbr3: 'COM' },
  { name: 'Congo', code: '+242', abbr: 'CG', abbr3: 'COG' },
  { name: 'Congo, Democratic Republic of the Congo', code: '+242', abbr: 'CD', abbr3: 'COD' },
  { name: 'Cook Islands', code: '+682', abbr: 'CK', abbr3: 'COK' },
  { name: 'Costa Rica', code: '+506', abbr: 'CR', abbr3: 'CRI' },
  { name: "Cote D'Ivoire", code: '+225', abbr: 'CI', abbr3: 'CIV' },
  { name: 'Croatia', code: '+385', abbr: 'HR', abbr3: 'HRV' },
  { name: 'Cuba', code: '+53', abbr: 'CU', abbr3: 'CUB' },
  { name: 'Curacao', code: '+599', abbr: 'CW', abbr3: 'CUW' },
  { name: 'Cyprus', code: '+357', abbr: 'CY', abbr3: 'CYP' },
  { name: 'Czech Republic', code: '+420', abbr: 'CZ', abbr3: 'CZE' },
  { name: 'Denmark', code: '+45', abbr: 'DK', abbr3: 'DNK' },
  { name: 'Djibouti', code: '+253', abbr: 'DJ', abbr3: 'DJI' },
  { name: 'Dominica', code: '+1767', abbr: 'DM', abbr3: 'DMA' },
  { name: 'Dominican Republic', code: '+1809', abbr: 'DO', abbr3: 'DOM' },
  { name: 'Ecuador', code: '+593', abbr: 'EC', abbr3: 'ECU' },
  { name: 'Egypt', code: '+20', abbr: 'EG', abbr3: 'EGY' },
  { name: 'El Salvador', code: '+503', abbr: 'SV', abbr3: 'SLV' },
  { name: 'Equatorial Guinea', code: '+240', abbr: 'GQ', abbr3: 'GNQ' },
  { name: 'Eritrea', code: '+291', abbr: 'ER', abbr3: 'ERI' },
  { name: 'Estonia', code: '+372', abbr: 'EE', abbr3: 'EST' },
  { name: 'Ethiopia', code: '+251', abbr: 'ET', abbr3: 'ETH' },
  { name: 'Falkland Islands (Malvinas)', code: '+500', abbr: 'FK', abbr3: 'FLK' },
  { name: 'Faroe Islands', code: '+298', abbr: 'FO', abbr3: 'FRO' },
  { name: 'Fiji', code: '+679', abbr: 'FJ', abbr3: 'FJI' },
  { name: 'Finland', code: '+358', abbr: 'FI', abbr3: 'FIN' },
  { name: 'France', code: '+33', abbr: 'FR', abbr3: 'FRA' },
  { name: 'French Guiana', code: '+594', abbr: 'GF', abbr3: 'GUF' },
  { name: 'French Polynesia', code: '+689', abbr: 'PF', abbr3: 'PYF' },
  { name: 'French Southern Territories', code: '+262', abbr: 'TF', abbr3: 'ATF' },
  { name: 'Gabon', code: '+241', abbr: 'GA', abbr3: 'GAB' },
  { name: 'Gambia', code: '+220', abbr: 'GM', abbr3: 'GMB' },
  { name: 'Georgia', code: '+995', abbr: 'GE', abbr3: 'GEO' },
  { name: 'Germany', code: '+49', abbr: 'DE', abbr3: 'DEU' },
  { name: 'Ghana', code: '+233', abbr: 'GH', abbr3: 'GHA' },
  { name: 'Gibraltar', code: '+350', abbr: 'GI', abbr3: 'GIB' },
  { name: 'Greece', code: '+30', abbr: 'GR', abbr3: 'GRC' },
  { name: 'Greenland', code: '+299', abbr: 'GL', abbr3: 'GRL' },
  { name: 'Grenada', code: '+1473', abbr: 'GD', abbr3: 'GRD' },
  { name: 'Guadeloupe', code: '+590', abbr: 'GP', abbr3: 'GLP' },
  { name: 'Guam', code: '+1671', abbr: 'GU', abbr3: 'GUM' },
  { name: 'Guatemala', code: '+502', abbr: 'GT', abbr3: 'GTM' },
  { name: 'Guernsey', code: '+44', abbr: 'GG', abbr3: 'GGY' },
  { name: 'Guinea', code: '+224', abbr: 'GN', abbr3: 'GIN' },
  { name: 'Guinea-Bissau', code: '+245', abbr: 'GW', abbr3: 'GNB' },
  { name: 'Guyana', code: '+592', abbr: 'GY', abbr3: 'GUY' },
  { name: 'Haiti', code: '+509', abbr: 'HT', abbr3: 'HTI' },
  { name: 'Holy See (Vatican City State)', code: '+39', abbr: 'VA', abbr3: 'VAT' },
  { name: 'Honduras', code: '+504', abbr: 'HN', abbr3: 'HND' },
  { name: 'Hong Kong', code: '+852', abbr: 'HK', abbr3: 'HKG' },
  { name: 'Hungary', code: '+36', abbr: 'HU', abbr3: 'HUN' },
  { name: 'Iceland', code: '+354', abbr: 'IS', abbr3: 'ISL' },
  { name: 'India', code: '+91', abbr: 'IN', abbr3: 'IND' },
  { name: 'Indonesia', code: '+62', abbr: 'ID', abbr3: 'IDN' },
  { name: 'Iran, Islamic Republic of', code: '+98', abbr: 'IR', abbr3: 'IRN' },
  { name: 'Iraq', code: '+964', abbr: 'IQ', abbr3: 'IRQ' },
  { name: 'Ireland', code: '+353', abbr: 'IE', abbr3: 'IRL' },
  { name: 'Isle of Man', code: '+44', abbr: 'IM', abbr3: 'IMN' },
  { name: 'Israel', code: '+972', abbr: 'IL', abbr3: 'ISR' },
  { name: 'Italy', code: '+39', abbr: 'IT', abbr3: 'ITA' },
  { name: 'Jamaica', code: '+1876', abbr: 'JM', abbr3: 'JAM' },
  { name: 'Japan', code: '+81', abbr: 'JP', abbr3: 'JPN' },
  { name: 'Jersey', code: '+44', abbr: 'JE', abbr3: 'JEY' },
  { name: 'Jordan', code: '+962', abbr: 'JO', abbr3: 'JOR' },
  { name: 'Kazakhstan', code: '+7', abbr: 'KZ', abbr3: 'KAZ' },
  { name: 'Kiribati', code: '+686', abbr: 'KI', abbr3: 'KIR' },
  { name: "Korea, Democratic People's Republic of", code: '+850', abbr: 'KP', abbr3: 'PRK' },
  { name: 'Korea, Republic of', code: '+82', abbr: 'KR', abbr3: 'KOR' },
  { name: 'Kosovo', code: '+383', abbr: 'XK', abbr3: 'XKX' },
  { name: 'Kuwait', code: '+965', abbr: 'KW', abbr3: 'KWT' },
  { name: 'Kyrgyzstan', code: '+996', abbr: 'KG', abbr3: 'KGZ' },
  { name: "Lao People's Democratic Republic", code: '+856', abbr: 'LA', abbr3: 'LAO' },
  { name: 'Latvia', code: '+371', abbr: 'LV', abbr3: 'LVA' },
  { name: 'Lebanon', code: '+961', abbr: 'LB', abbr3: 'LBN' },
  { name: 'Lesotho', code: '+266', abbr: 'LS', abbr3: 'LSO' },
  { name: 'Liberia', code: '+231', abbr: 'LR', abbr3: 'LBR' },
  { name: 'Libyan Arab Jamahiriya', code: '+218', abbr: 'LY', abbr3: 'LBY' },
  { name: 'Liechtenstein', code: '+423', abbr: 'LI', abbr3: 'LIE' },
  { name: 'Lithuania', code: '+370', abbr: 'LT', abbr3: 'LTU' },
  { name: 'Luxembourg', code: '+352', abbr: 'LU', abbr3: 'LUX' },
  { name: 'Macao', code: '+853', abbr: 'MO', abbr3: 'MAC' },
  { name: 'Macedonia, the Former Yugoslav Republic of', code: '+389', abbr: 'MK', abbr3: 'MKD' },
  { name: 'Madagascar', code: '+261', abbr: 'MG', abbr3: 'MDG' },
  { name: 'Malawi', code: '+265', abbr: 'MW', abbr3: 'MWI' },
  { name: 'Malaysia', code: '+60', abbr: 'MY', abbr3: 'MYS' },
  { name: 'Maldives', code: '+960', abbr: 'MV', abbr3: 'MDV' },
  { name: 'Mali', code: '+223', abbr: 'ML', abbr3: 'MLI' },
  { name: 'Malta', code: '+356', abbr: 'MT', abbr3: 'MLT' },
  { name: 'Marshall Islands', code: '+692', abbr: 'MH', abbr3: 'MHL' },
  { name: 'Martinique', code: '+596', abbr: 'MQ', abbr3: 'MTQ' },
  { name: 'Mauritania', code: '+222', abbr: 'MR', abbr3: 'MRT' },
  { name: 'Mauritius', code: '+230', abbr: 'MU', abbr3: 'MUS' },
  { name: 'Mayotte', code: '+262', abbr: 'YT', abbr3: 'MYT' },
  { name: 'Mexico', code: '+52', abbr: 'MX', abbr3: 'MEX' },
  { name: 'Micronesia, Federated States of', code: '+691', abbr: 'FM', abbr3: 'FSM' },
  { name: 'Moldova, Republic of', code: '+373', abbr: 'MD', abbr3: 'MDA' },
  { name: 'Monaco', code: '+377', abbr: 'MC', abbr3: 'MCO' },
  { name: 'Mongolia', code: '+976', abbr: 'MN', abbr3: 'MNG' },
  { name: 'Montenegro', code: '+382', abbr: 'ME', abbr3: 'MNE' },
  { name: 'Montserrat', code: '+1664', abbr: 'MS', abbr3: 'MSR' },
  { name: 'Morocco', code: '+212', abbr: 'MA', abbr3: 'MAR' },
  { name: 'Mozambique', code: '+258', abbr: 'MZ', abbr3: 'MOZ' },
  { name: 'Myanmar', code: '+95', abbr: 'MM', abbr3: 'MMR' },
  { name: 'Namibia', code: '+264', abbr: 'NA', abbr3: 'NAM' },
  { name: 'Nauru', code: '+674', abbr: 'NR', abbr3: 'NRU' },
  { name: 'Nepal', code: '+977', abbr: 'NP', abbr3: 'NPL' },
  { name: 'Netherlands', code: '+31', abbr: 'NL', abbr3: 'NLD' },
  { name: 'New Caledonia', code: '+687', abbr: 'NC', abbr3: 'NCL' },
  { name: 'New Zealand', code: '+64', abbr: 'NZ', abbr3: 'NZL' },
  { name: 'Nicaragua', code: '+505', abbr: 'NI', abbr3: 'NIC' },
  { name: 'Niger', code: '+227', abbr: 'NE', abbr3: 'NER' },
  { name: 'Niue', code: '+683', abbr: 'NU', abbr3: 'NIU' },
  { name: 'Norfolk Island', code: '+672', abbr: 'NF', abbr3: 'NFK' },
  { name: 'Northern Mariana Islands', code: '+1670', abbr: 'MP', abbr3: 'MNP' },
  { name: 'Norway', code: '+47', abbr: 'NO', abbr3: 'NOR' },
  { name: 'Oman', code: '+968', abbr: 'OM', abbr3: 'OMN' },
  { name: 'Pakistan', code: '+92', abbr: 'PK', abbr3: 'PAK' },
  { name: 'Palau', code: '+680', abbr: 'PW', abbr3: 'PLW' },
  { name: 'Palestinian Territory, Occupied', code: '+970', abbr: 'PS', abbr3: 'PSE' },
  { name: 'Panama', code: '+507', abbr: 'PA', abbr3: 'PAN' },
  { name: 'Papua New Guinea', code: '+675', abbr: 'PG', abbr3: 'PNG' },
  { name: 'Paraguay', code: '+595', abbr: 'PY', abbr3: 'PRY' },
  { name: 'Peru', code: '+51', abbr: 'PE', abbr3: 'PER' },
  { name: 'Philippines', code: '+63', abbr: 'PH', abbr3: 'PHL' },
  { name: 'Pitcairn', code: '+64', abbr: 'PN', abbr3: 'PCN' },
  { name: 'Poland', code: '+48', abbr: 'PL', abbr3: 'POL' },
  { name: 'Portugal', code: '+351', abbr: 'PT', abbr3: 'PRT' },
  { name: 'Puerto Rico', code: '+1787', abbr: 'PR', abbr3: 'PRI' },
  { name: 'Qatar', code: '+974', abbr: 'QA', abbr3: 'QAT' },
  { name: 'Reunion', code: '+262', abbr: 'RE', abbr3: 'REU' },
  { name: 'Romania', code: '+40', abbr: 'RO', abbr3: 'ROU' },
  { name: 'Russian Federation', code: '+7', abbr: 'RU', abbr3: 'RUS' },
  { name: 'Rwanda', code: '+250', abbr: 'RW', abbr3: 'RWA' },
  { name: 'Saint Barthelemy', code: '+590', abbr: 'BL', abbr3: 'BLM' },
  { name: 'Saint Helena', code: '+290', abbr: 'SH', abbr3: 'SHN' },
  { name: 'Saint Kitts and Nevis', code: '+1869', abbr: 'KN', abbr3: 'KNA' },
  { name: 'Saint Lucia', code: '+1758', abbr: 'LC', abbr3: 'LCA' },
  { name: 'Saint Martin', code: '+590', abbr: 'MF', abbr3: 'MAF' },
  { name: 'Saint Pierre and Miquelon', code: '+508', abbr: 'PM', abbr3: 'SPM' },
  { name: 'Saint Vincent and the Grenadines', code: '+1784', abbr: 'VC', abbr3: 'VCT' },
  { name: 'Samoa', code: '+684', abbr: 'WS', abbr3: 'WSM' },
  { name: 'San Marino', code: '+378', abbr: 'SM', abbr3: 'SMR' },
  { name: 'Sao Tome and Principe', code: '+239', abbr: 'ST', abbr3: 'STP' },
  { name: 'Saudi Arabia', code: '+966', abbr: 'SA', abbr3: 'SAU' },
  { name: 'Senegal', code: '+221', abbr: 'SN', abbr3: 'SEN' },
  { name: 'Serbia', code: '+381', abbr: 'RS', abbr3: 'SRB' },
  { name: 'Seychelles', code: '+248', abbr: 'SC', abbr3: 'SYC' },
  { name: 'Sierra Leone', code: '+232', abbr: 'SL', abbr3: 'SLE' },
  { name: 'Singapore', code: '+65', abbr: 'SG', abbr3: 'SGP' },
  { name: 'Sint Maarten', code: '+1', abbr: 'SX', abbr3: 'SXM' },
  { name: 'Slovakia', code: '+421', abbr: 'SK', abbr3: 'SVK' },
  { name: 'Slovenia', code: '+386', abbr: 'SI', abbr3: 'SVN' },
  { name: 'Solomon Islands', code: '+677', abbr: 'SB', abbr3: 'SLB' },
  { name: 'Somalia', code: '+252', abbr: 'SO', abbr3: 'SOM' },
  { name: 'South Africa', code: '+27', abbr: 'ZA', abbr3: 'ZAF' },
  { name: 'South Georgia and the South Sandwich Islands', code: '+500', abbr: 'GS', abbr3: 'SGS' },
  { name: 'South Sudan', code: '+211', abbr: 'SS', abbr3: 'SSD' },
  { name: 'Spain', code: '+34', abbr: 'ES', abbr3: 'ESP' },
  { name: 'Sri Lanka', code: '+94', abbr: 'LK', abbr3: 'LKA' },
  { name: 'Sudan', code: '+249', abbr: 'SD', abbr3: 'SDN' },
  { name: 'Suriname', code: '+597', abbr: 'SR', abbr3: 'SUR' },
  { name: 'Svalbard and Jan Mayen', code: '+47', abbr: 'SJ', abbr3: 'SJM' },
  { name: 'Swaziland', code: '+268', abbr: 'SZ', abbr3: 'SWZ' },
  { name: 'Sweden', code: '+46', abbr: 'SE', abbr3: 'SWE' },
  { name: 'Switzerland', code: '+41', abbr: 'CH', abbr3: 'CHE' },
  { name: 'Syrian Arab Republic', code: '+963', abbr: 'SY', abbr3: 'SYR' },
  { name: 'Taiwan, Province of China', code: '+886', abbr: 'TW', abbr3: 'TWN' },
  { name: 'Tajikistan', code: '+992', abbr: 'TJ', abbr3: 'TJK' },
  { name: 'Tanzania, United Republic of', code: '+255', abbr: 'TZ', abbr3: 'TZA' },
  { name: 'Thailand', code: '+66', abbr: 'TH', abbr3: 'THA' },
  { name: 'Timor-Leste', code: '+670', abbr: 'TL', abbr3: 'TLS' },
  { name: 'Togo', code: '+228', abbr: 'TG', abbr3: 'TGO' },
  { name: 'Tokelau', code: '+690', abbr: 'TK', abbr3: 'TKL' },
  { name: 'Tonga', code: '+676', abbr: 'TO', abbr3: 'TON' },
  { name: 'Trinidad and Tobago', code: '+1868', abbr: 'TT', abbr3: 'TTO' },
  { name: 'Tunisia', code: '+216', abbr: 'TN', abbr3: 'TUN' },
  { name: 'Turkey', code: '+90', abbr: 'TR', abbr3: 'TUR' },
  { name: 'Turkmenistan', code: '+993', abbr: 'TM', abbr3: 'TKM' },
  { name: 'Turks and Caicos Islands', code: '+1649', abbr: 'TC', abbr3: 'TCA' },
  { name: 'Tuvalu', code: '+688', abbr: 'TV', abbr3: 'TUV' },
  { name: 'Uganda', code: '+256', abbr: 'UG', abbr3: 'UGA' },
  { name: 'Ukraine', code: '+380', abbr: 'UA', abbr3: 'UKR' },
  { name: 'United Arab Emirates', code: '+971', abbr: 'AE', abbr3: 'ARE' },
  { name: 'United Kingdom', code: '+44', abbr: 'GB', abbr3: 'GBR' },
  { name: 'United States', code: '+1', abbr: 'US', abbr3: 'USA' },
  { name: 'United States Minor Outlying Islands', code: '+1', abbr: 'UM', abbr3: 'UMI' },
  { name: 'Uruguay', code: '+598', abbr: 'UY', abbr3: 'URY' },
  { name: 'Uzbekistan', code: '+998', abbr: 'UZ', abbr3: 'UZB' },
  { name: 'Vanuatu', code: '+678', abbr: 'VU', abbr3: 'VUT' },
  { name: 'Venezuela', code: '+58', abbr: 'VE', abbr3: 'VEN' },
  { name: 'Viet Nam', code: '+84', abbr: 'VN', abbr3: 'VNM' },
  { name: 'Virgin Islands, British', code: '+1284', abbr: 'VG', abbr3: 'VGB' },
  { name: 'Virgin Islands, U.s.', code: '+1340', abbr: 'VI', abbr3: 'VIR' },
  { name: 'Wallis and Futuna', code: '+681', abbr: 'WF', abbr3: 'WLF' },
  { name: 'Western Sahara', code: '+212', abbr: 'EH', abbr3: 'ESH' },
  { name: 'Yemen', code: '+967', abbr: 'YE', abbr3: 'YEM' },
  { name: 'Zambia', code: '+260', abbr: 'ZM', abbr3: 'ZMB' },
  { name: 'Zimbabwe', code: '+263', abbr: 'ZW', abbr3: 'ZWE' }
];